from django.urls import path
from .views import (
    ListCreateView,
    ListDeleteView,
    ListRetrieveView,
    ListUpdateView,
    ProjectCreateView,
    ProjectDeleteView,
    ProjectListView,
    ProjectRetrieveView,
    ProjectUpdateView,
    BoardCreateView,
    BoardDeleteView,
    BoardListView,
    BoardUpdateView,
    BoardRetrieveView,
    TaskCreateView,
    TaskDeleteView,
    TaskRetrieveView,
    TaskUpdateView,
)

urlpatterns = [
    path("projects/", ProjectListView.as_view(), name="project-list"),
    path("projects/<id>", ProjectRetrieveView.as_view(), name="project-retrieve"),
    path("projects/update/<id>", ProjectUpdateView.as_view(), name="project-update"),
    path("projects/create/", ProjectCreateView.as_view(), name="project-create"),
    path("projects/delete/<id>", ProjectDeleteView.as_view(), name="project-delete"),
    path("boards/", BoardListView.as_view(), name="board-list"),  # won't be used
    path("boards/<id>", BoardRetrieveView.as_view(), name="board-retrieve"),
    path("boards/update/<id>", BoardUpdateView.as_view(), name="board-update"),
    path("boards/create/<id>", BoardCreateView.as_view(), name="board-update"),
    path("boards/delete/<id>", BoardDeleteView.as_view(), name="board-destroy"),
    path("lists/<id>", ListRetrieveView.as_view(), name="list-retrieve"),
    path("lists/update/<id>", ListUpdateView.as_view(), name="list-update"),
    path("lists/create/<id>", ListCreateView.as_view(), name="list-create"),
    path("lists/delete/<id>", ListDeleteView.as_view(), name="list-delete"),
    path("tasks/<id>", TaskRetrieveView.as_view(), name="task-retrieve"),
    path("tasks/update/<id>", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/create/<id>", TaskCreateView.as_view(), name="task-create"),
    path("tasks/delete/<id>", TaskDeleteView.as_view(), name="task-delete"),
]
